import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of your plugin
*/
`;

const prod = process.argv[2] === "production";

// Load .env for OBSIDIAN_VAULT
try {
	const env = readFileSync(".env", "utf8");
	for (const line of env.split("\n")) {
		const match = line.match(/^\s*([\w]+)\s*=\s*(.+)\s*$/);
		if (match) process.env[match[1]] = match[2];
	}
} catch {}

let vaultDir;
if (process.env.OBSIDIAN_VAULT) {
	const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
	vaultDir = join(process.env.OBSIDIAN_VAULT, ".obsidian", "plugins", manifest.id);
}

const copyToVaultPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd(() => {
			if (!vaultDir) return;
			mkdirSync(vaultDir, { recursive: true });
			for (const file of ["main.js", "manifest.json", "styles.css"]) {
				copyFileSync(file, join(vaultDir, file));
			}
			console.log(`Copied to ${vaultDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
